function save_kernels(filename, kernel_3d)

fid = fopen(filename,'wt');
for i=1:length(kernel_3d)
  fprintf(fid,'(%d,%d,%d)\t\t(%d,%d)\t\t%s\t\t\t\t%s\n', ...
                                   kernel_3d(i).prev_length(1), ...
                                   kernel_3d(i).prev_length(2), ...
                                   kernel_3d(i).prev_length(3),
                                   kernel_3d(i).length(1), ...
                                   kernel_3d(i).length(2), ...
                                   mat2str(kernel_3d(i).factors_1), ...
                                   mat2str(kernel_3d(i).factors_2));
end
fclose(fid);




