This document contains notes for servers that may be important to
rocFFT development.

* lockhart
slurm is available on the lockhart cluster.  Launch jobs from the
login node.  Note that one can't compile from the login node, so
it's best to launch a job just for compilation:

srun --gpus-per-node=0 --time=30:00 --pty /bin/bash

module load emacs

module load craype-accel-amd-gfx90a
module load rocm/6.1.3
export MPICH_GPU_SUPPORT_ENABLED=1
module load cray-pals

* Frontier
module purge
module load rocm/6.2
module load PrgEnv-cray/8.3.3
module load craype-accel-amd-gfx90a
module load cray-python/3.9.13.1
module load boost
module load cray-mpich

export MPICH_GPU_SUPPORT_ENABLED=1
export PE_MPICH_GTL_DIR_amd_gfx90a="-L${CRAY_MPICH_ROOTDIR}/gtl/lib"
export PE_MPICH_GTL_LIBS_amd_gfx90a="-lmpi_gtl_hsa"

* lumi
Obtaining an account on LUMI - Supercomputer in Finland (rank 5 world Top500)

Contact Antao, Samuel to make the request, and he'll reach out to Pekka to pre-approve it. If approved, he will inform Lumi center to expect your registration.
A good idea for justification is to say that you'll get experiments on FFT scalability useful for HPC applications related to AMD, such as Quantum Espresso.
Follow the procedure to formally request an account:
Please fill in the following form: https://my.csc.fi/csc-customer-registration
When filling the table, choose that you have been invited to be a member of existing project and add the following information regarding the project:

Project number: 462000125
Project manager: Pekka Manninen
Project manager e-mail: pekka.manninen@csc.fi
Project manager organization: CSC

module load PrgEnv-cray/8.5.0
module load cce/17.0.1
module load craype-accel-amd-gfx90a
module load rocm/6.0.3
export MPICH_GPU_SUPPORT_ENABLED=1
* MPI
** mpich
