#!/usr/bin/env python3

import subprocess
import pathlib
import sys
import os

def pdf2emf(pdfname):
    """Convert PDF to EMF."""
    pdf = pdfname
    svg = pdfname[0:-4] + ".svg"
    emf = pdfname[0:-4] + ".emf"
    subprocess.check_call(["pdf2svg", pdf, svg])
    # Older versions of inkscape use -M.
    #subprocess.check_call(["inkscape", svg, "-M", emf])
    subprocess.check_call(["inkscape", svg, "--export-filename", emf])
    return emf

if len(sys.argv) != 2:
    print("Please pdf filename")
    sys.exit(1)

pdfname = sys.argv[1]

if not os.path.isfile(pdfname):
    print(pdfname, "does not exist; exiting")
    sys.exit(1)

if not pdfname.endswith(".pdf"):
    print(pdfname, "does not end in .pdf; exiting")
    sys.exit(1)

    

pdf2emf(pdfname)
