#!/usr/bin/env python3

import dataclasses
from dataclasses import dataclass, field
from typing import *
import sys

import functools
import subprocess
from pathlib import Path as path

#
# Helpers
#

def join(sep, n):
    if isinstance(n, BaseNode):
        return sep.join([ str(x) for x in n.args ])
    return sep.join([ str(x) for x in n ])


def declarations(xs):
    return [ x.declaration() for x in xs ]


def format(code):
    p = subprocess.run(['clang-format-10', '-style=file'], stdout=subprocess.PIPE, input=str(code), encoding='ascii', check=True)
    return p.stdout


def format_and_write(fname, code):
    code = format(code)
    f = path(fname)
    if f.exists():
        existing = f.read_text()
        if existing == code:
            return
    f.write_text(code)


def walk(x):
    if isinstance(x, BaseNode):
        yield x
        for a in x.args:
            if isinstance(a, BaseNode):
                yield from a
            else:
                yield a

def depth_first(x, f):
    if isinstance(x, BaseNode):
        y = type(x)()
        y.args = [ depth_first(a, f) for a in x.args ]
        return f(y)
    return f(x)

#
# Code generator classes
#

class BaseNode:
    args: List[Any]
    kwargs = None
    sep: str = None
    def __init__(self, *args, **kwargs):
        self.args = list(args)
        self.kwargs = kwargs
        if hasattr(self, '__post_init__'):
            getattr(self, '__post_init__')(self)
    def __str__(self):
        if self.sep is not None:
            return self.sep.join([str(x) for x in self.args])
        return str(self.args[0])
    def __iter__(self):
        return walk(self)


class BaseNodeOps(BaseNode):
    def __add__(self, a):
        return Add(self, a)
    def __radd__(self, a):
        return Add(a, self)
    def __sub__(self, a):
        return Sub(self, a)
    def __rsub__(self, a):
        return Sub(a, self)
    def __mul__(self, a):
        return Multiply(self, a)
    def __rmul__(self, a):
        return Multiply(a, self)
    def __mod__(self, a):
        return Mod(self, a)
    def __rmod__(self, a):
        return Mod(a, self)
    def __truediv__(self, a):
        return Divide(self, a)
    def __rtruediv__(self, a):
        return Divide(a, self)
    def __ge__(self, a):
        return GreaterEqual(self, a)
    def __lt__(self, a):
        return Less(self, a)


class StatementList(BaseNode):
    def __add__(self, lst):
        if isinstance(lst, list):
            self.args.extend(lst)
        elif isinstance(lst, StatementList):
            self.args.extend(lst.statements)
        else:
            self.args.append(lst)
        return self


class ArgumentList(BaseNode):
    def __str__(self):
        args = []
        for x in self.args:
            if isinstance(x, Variable):
                args.append(x.argument())
            else:
                args.append(str(x))
        return ', '.join(args)


class TemplateList(ArgumentList):
    pass


class String(BaseNode):
    pass


class Declaration(String):
    pass


class Address(BaseNode):
    def __str__(self):
        return '&' + self.args[0]


def make_binary(separator):
    def decorator(target):
        target.sep = separator
        return target
    return decorator


@make_binary('.')
class Component(BaseNodeOps):
    pass

@make_binary(' + ')
class Add(BaseNodeOps):
    pass

@make_binary(' - ')
class Sub(BaseNodeOps):
    pass

@make_binary(' / ')
class Divide(BaseNodeOps):
    pass

@make_binary(' * ')
class Multiply(BaseNodeOps):
    pass

class Assign(BaseNode):
    def __str__(self):
        return str(self.args[0]) + ' = ' + str(self.args[1]) + ';'

@make_binary(' % ')
class Mod(BaseNodeOps):
    pass

@make_binary(' >= ')
class GreaterEqual(BaseNodeOps):
    pass

@make_binary(' < ')
class Less(BaseNodeOps):
    pass

class ArrayElement(BaseNodeOps):
    @property
    def variable(self):
        return self.args[0]
    @property
    def index(self):
        return self.args[1]

    def __str__(self) -> str:
        return str(self.variable) + '[' + str(self.index) + ']'

    def address(self):
        return Address(str(self))

    @property
    def x(self):
        return Component(str(self), 'x')
    @property
    def y(self):
        return Component(str(self), 'y')


class Variable(BaseNodeOps):
    '''Variable.'''
    @property
    def name(self):
        return self.args[0]
    @property
    def type(self):
        return self.args[1]
    @property
    def size(self):
        return self.args[2]
    @property
    def array(self):
        return self.args[3]
    def __str__(self) -> str:
        return str(self.name)
    def __init__(self, name=None, type=None, size=None, array=False):
        self.args = [ name, type, size, array ]

    @property
    def x(self):
        return Component(self.name, 'x')
    @property
    def y(self):
        return Component(self.name, 'y')
    def address(self):
        return Address(self.name)
    def declaration(self):
        if self.size is not None:
            return Declaration(f'{self.type} {self.name}[{self.size}];')
        return Declaration(f'{self.type} {self.name};')
    def argument(self):
        if self.array:
            return f'{self.type} *{self.name}'
        return f'{self.type} {self.name}'
    def __getitem__(self, idx):
        return ArrayElement(self.name, idx)

class ComplexLiteral(BaseNodeOps):
    def __str__(self):
        return '{' + str(self.args[0]) + ', ' + str(self.args[1]) + '}'


class Group(BaseNodeOps):
    def __str__(self):
        return '(' + str(self.args[0]) + ')'

B = Group

class Block(BaseNode):
    def __str__(self):
        return '{' + join('\n', self.args) + '}'


class If(BaseNode):
    @property
    def condition(self):
        return self.args[0]
    @property
    def body(self):
        return self.args[1]
    def __str__(self) -> str:
        f = 'if( ' + str(self.condition) + ')'
        f += '{' + join('\n', self.body) + '}'
        return f

class Function(BaseNode):
    @property
    def name(self):
        return self.args[0]
    @property
    def arguments(self):
        return self.args[1]
    @property
    def templates(self):
        return self.args[2]
    @property
    def qualifier(self):
        return self.args[3]
    @property
    def body(self):
        return self.args[4]

    def __init__(self, name=None, arguments=None, templates=None, body=None, qualifier=None):
        self.args = [ name, arguments, templates, qualifier, body ]

    def __str__(self) -> str:
        f = ''
        if self.templates:
            f += 'template<' + str(self.templates) + '>'
        if self.qualifier is not None:
            f += self.qualifier + ' '
        f += ' void ' + self.name
        f += '(' + str(self.arguments) + ')'
        f += '{' + join('\n', self.body) + '}'
        return f


class Call(BaseNode):
    @property
    def name(self):
        return self.args[0]
    @property
    def arguments(self):
        return self.args[1]
    @property
    def templates(self):
        return self.args[2]
    @property
    def launch_params(self):
        return self.args[3]

    def __init__(self, name=None, arguments=None, templates=None, launch_params=None):
        self.args = [ name, arguments, templates, launch_params ]

    def __str__(self) -> str:
        f = self.name
        if self.templates:
            f += '<' + join(', ', self.templates) + '>'
        if self.launch_params:
            f += '<<<' + join(',  ', self.launch_params) + '>>>'
        f += '(' + join(', ', self.arguments) + ');'
        return f

# class Define:
#     '''CPP definition.'''
#     lhs: str
#     rhs: str
#     def __str__(self) -> str:
#         return f'#define {str(self.lhs)} {str(self.rhs)}'

return_statement = String("return;")
line_break = String("\n\n")
sync_threads = String("__syncthreads();")

#
# Stockham FFTs!
#

def product(factors):
    if factors:
        return functools.reduce(lambda a, b: a*b, factors)
    return 1

@dataclass
class LaunchParams:
    batches_per_block: int
    threads_per_block: int

def get_launch_params(factors, bytes_per_element=16, lds_byte_limit=32*1024):
    length = product(factors)
    bytes_per_batch = length * bytes_per_element
    max_factor = max(factors)

    # do as many batches-per-block as we can without going over 32KiB
    # per block; also don't go beyond 256 threads-per-block
    bpb = lds_byte_limit // bytes_per_batch
    while (length // max_factor) * bpb > 64:
        bpb -= 1
    return LaunchParams(bpb, (length // max_factor) * bpb)


def stockham_device(factors):
    length = product(factors)

    scalar_type = Variable('scalar_type', 'typename')
    stride_in = Variable('stride_in', 'int')
    stride_out = Variable('stride_out', 'int')
    offset_in = Variable('offset_in', 'int')
    offset_out = Variable('offset_out', 'int')
    offset_lds = Variable('offset_lds', 'int')
    thread = Variable('thread', 'int')
    thread_id = Variable('threadIdx.x', 'int')

    W = Variable('W', 'scalar_type')
    t = Variable('t', 'scalar_type')
    R = Variable('R', 'scalar_type', 2*max(factors))
    X = Variable('lds', 'scalar_type', array=True)
    Z = Variable('inout', 'scalar_type', array=True)
    T = Variable('twiddles', 'const scalar_type', array=True)

    width0 = length // factors[0]

    def load_global():
        stmts = [ Assign(thread, thread_id % width0),
                  line_break ]
        for b in range(length // width):
            idx = thread + b * width
            stmts += [ Assign(X[offset_lds + idx], Z[offset_in + idx]) ]
        return stmts

    def load_lds():
        stmts = [ Assign(thread, thread_id % width0 + nsubpass * width0),
                  line_break ]
        for w in range(width):
            idx = offset_lds + thread + length//width * w
            stmts += [ Assign(R[nsubpass*width+w], X[idx]) ]
        return stmts

    def twiddle():
        stmts = [ Assign(thread, thread_id % width0 + nsubpass * width0),
                  line_break ]
        for w in range(1, width):
            tidx = nheight - 1 + w - 1 + (width - 1) * B(thread % nheight)
            ridx = nsubpass*width + w
            stmts += [ Assign(W, T[tidx]),
                       Assign(t.x, W.x * R[ridx].x - W.y * R[ridx].y),
                       Assign(t.y, W.y * R[ridx].x + W.x * R[ridx].y),
                       Assign(R[ridx], t),
                       line_break ]
        return stmts

    def butterfly():
        return [ Call(f'FwdRad{width}B1', arguments=ArgumentList(*[R[nsubpass*width+w].address() for w in range(width)])) ]

    def store_lds():
        stmts = [ Assign(thread, thread_id % width0 + nsubpass * width0),
                  line_break ]
        for w in range(width):
            idx = offset_lds + B(thread / nheight) * (width * nheight) + thread % nheight + w * nheight
            stmts += [ Assign(X[idx], R[nsubpass*width+w]) ]
        stmts += [ line_break ]
        return stmts


    def add_work(generator):
        if nsubpass < height - 1:
            return generator()
        needs_work = thread_id % width0 + nsubpass * width0 < length // width
        return If(needs_work, generator())


    width = length // factors[0]

    body = StatementList()
    body += declarations([thread, R, W, t])
    body += load_global()
    body += line_break

    #
    # tranform
    #
    for npass, width in enumerate(factors):
        nheight = product(factors[:npass])
        body += sync_threads

        #height = max(2, width0 // width)
        height = 2

        for nsubpass in range(height):
            body += add_work(load_lds)
        if npass > 0:
            for nsubpass in range(height):
                body += add_work(twiddle)
        body += line_break
        for nsubpass in range(height):
            body += add_work(butterfly)
        body += line_break
        for nsubpass in range(height):
            body += add_work(store_lds)

        body += line_break


    # store global
    width = factors[0]
    body += sync_threads
    body += Assign(thread, thread_id % width0)
    for w in range(width):
        idx = thread + length//width * w
        body += Assign(Z[offset_out + idx], X[offset_lds + idx])

    return Function(f'forward_length{length}_device',
                   arguments = ArgumentList(Z, X, T, stride_in, stride_out, offset_in, offset_out, offset_lds),
                   templates = TemplateList(scalar_type),
                   body = body,
                   qualifier = '__device__')


def stockham_global(factors):
    length = product(factors)

    scalar_type = Variable('scalar_type', 'typename')
    inout       = Variable('inout', 'scalar_type', array=True)
    twiddles    = Variable('twiddles', 'const scalar_type', array=True)
    stride_in   = Variable('stride_in', 'int')
    stride_out  = Variable('stride_out', 'int')
    nbatch      = Variable('nbatch', 'int')


    body = StatementList()

    params = get_launch_params(factors)

    lds = Variable('lds', '__shared__ scalar_type', size=length * params.batches_per_block)
    block_id   = Variable('blockIdx.x')
    thread_id  = Variable('threadIdx.x')
    offset_in  = Variable('offset_in', 'int')
    offset_out = Variable('offset_out', 'int')
    offset_lds = Variable('offset_lds', 'int')
    batch      = Variable('batch', 'int')

    body += declarations([ lds, offset_in, offset_out, offset_lds, batch ])
    body += Assign(batch, block_id * params.batches_per_block + thread_id / (length // factors[0]));
    body += Assign(offset_in, length * batch)
    body += Assign(offset_out, length * batch)
    body += Assign(offset_lds, length * B(batch % params.batches_per_block))

    body += If(GreaterEqual(batch, nbatch), [ return_statement ])

    body += Call(f'forward_length{length}_device',
                 arguments = ArgumentList(inout, lds, twiddles, stride_in, stride_out, offset_in, offset_out, offset_lds),
                 templates = TemplateList(scalar_type))

    return Function(name = f'forward_length{length}',
                    qualifier = '__global__',
                    templates = TemplateList(scalar_type),
                    arguments = ArgumentList(inout, nbatch, twiddles, stride_in, stride_out),
                    body = body
                   )


def stockham_launch(factors):
    length = product(factors)

    scalar_type = Variable('scalar_type', 'typename')
    inout       = Variable('inout', 'scalar_type', array=True)
    twiddles    = Variable('twiddles', 'const scalar_type', array=True)
    stride_in   = Variable('stride_in', 'int')
    stride_out  = Variable('stride_out', 'int')
    nbatch      = Variable('nbatch', 'int')

    nblocks = Variable('nblocks', 'int')

    params = get_launch_params(factors)

    body = StatementList()
    body += declarations([ nblocks ])
    body += Assign(nblocks, B(nbatch + (params.batches_per_block - 1)) / params.batches_per_block)

    body += Call(f'forward_length{length}',
                 arguments = ArgumentList(inout, nbatch, twiddles, stride_in, stride_out),
                 templates = TemplateList(scalar_type),
                 launch_params = ArgumentList(nblocks, params.threads_per_block))

    return Function(f'forward_length{length}_launch',
                    templates = TemplateList(scalar_type),
                    arguments = ArgumentList(inout,  nbatch, twiddles, stride_in, stride_out),
                    body = body
                    )


def make_inout_planar_visitor(x):
    if isinstance(x, Assign):
        lhs, rhs = x.args

        # on rhs
        if isinstance(rhs, ArrayElement):
            name, index = rhs.args
            if name == "inout":
                return Assign(lhs,
                              ComplexLiteral(ArrayElement("inoutRe", index),
                                             ArrayElement("inoutIm", index)))

        # on lhs
        if isinstance(lhs, ArrayElement):
            name, index = lhs.args
            if name == "inout":
                return Block(Assign(ArrayElement("inoutRe", index),
                                    Component(rhs, 'x')),
                             Assign(ArrayElement("inoutIm", index),
                                    Component(rhs, 'y')))

    if isinstance(x, ArgumentList):
        args = []
        for arg in x.args:
            if isinstance(arg, Variable):
                if arg.name == "inout":
                    real_type = f'real_type_t<{arg.type}>'
                    args.append(Variable("inoutRe", type=real_type, array=True))
                    args.append(Variable("inoutIm", type=real_type, array=True))
                else:
                    args.append(arg)
            else:
                args.append(arg)
        return ArgumentList(*args)

    return x

def generate(factors):
    kernels = [ g(factors) for g in
                [stockham_device, stockham_global, stockham_launch] ]

    planar_kernels = [ depth_first(kernel, make_inout_planar_visitor) for kernel in kernels ]
    print(format(planar_kernels[0]))

    format_and_write("stockham_generated_kernel.h", join("\n", [ str(x) for x in kernels ]))

if __name__ == '__main__':
    factors = [ int(x) for x in sys.argv[1:] ]
    generate(factors)
